parser: babel-eslint

extends:
    - eslint:recommended
    - plugin:react/recommended

rules:
    strict: off
    react/prop-types: off

settings:
    react:
        version: "15.0"

env:
    es6: true
    browser: true

settings:
    react:
        version: detect
